### ISSUE TITLE
[ACME] Failure while building the Software with IIO

### ISSUE THREAD

**Issue by mdigiorgio** [BayLibre/manifests#1]
I'm trying to follow [this guide](http://wiki.baylibre.com/doku.php?id=acme:start#building_the_software_with_iio) to build the software with IIO and I'm running into two problems:
- `acme/production.xml` does not exist
- I tried with `acme/poky.xml` but then `acme-setup` does not exist

How could I solve this?

**Comment by mtitinger** [comment]
Hi Michele,

I recently renamed the xml file to buildroot.xml to differentiate with 
the poky version.

You can follow the guide starting with

repo init -u https://github.com/BayLibre/manifests.git -m acme/buildroot.xml

instead of the production.xml file.

sorry for the inconvenience.

Note that if your are familiar with poky you can follow this instead: 
https://github.com/BayLibre/meta-baylibre as we may switch over to poky.

Please let me know if you need any further help.

Kind regards,
Marc.

**Comment by mdigiorgio** [comment]
Hi Marc,

Thanks for updating the guide.

Kind regards,
Michele

**Comment by mdigiorgio** [comment]
Hello,

After I build the software with IIO and flash it to the sdcard I am not able to access the device via ssh with the default credentials (username = `root`, password blank). Where could I find those info?

Thanks,

Michele

**Comment by mtitinger** [comment]
Try adding you Id_rsa.pub key to /root/.ssh/authorized_keys  through the
serial console.

BR,M.
Le 17 mai 2016 6:38 PM, "Michele Di Giorgio" notifications@github.com a
écrit :

**Comment by mdigiorgio** [comment]
Now it works, thanks.

Michele
