### ISSUE TITLE
[ACME build] boot partition not created when flashing image to sdcard

### ISSUE THREAD

**Issue by mdigiorgio** [BayLibre/manifests#2]
Whenever I build the environment as per [ACME build (iio-version)](https://github.com/BayLibre/manifests#acme-build-environment-iio-version) and flash the image to the sdcard, I only get the filesystem without the boot partition. What I do is to manually create it and copy the relevant files, so that the board can correctly boot.

**Comment by superna9999** [comment]
Hello,

We are currently switching to a Yocto based build system in order to generate the IIO version of the ACME BeagleBone black images.
The Yocto build system provides a way to build a complete sdcard image, in a clean and reproductible way.

You can either:
- Test our initial beta image release : https://github.com/baylibre-acme/ACME/releases/tag/b0
- Re-build an image: https://github.com/baylibre-acme/ACME (Re-building won't the recommended way of using ACME)

We will be happy to have comments about this new distribution and make it simpler to use.
FYI, this new distribution is still in testing phase and is not publicly announced, and having such reports will help us move faster to a stable release.

Regards,
Neil

**Comment by mdigiorgio** [comment]
Hello Neil,

Thanks for your reply.

I tried to use the beta image. It correctly creates the two partitions on the sd-card and it seems to work fine. I'll provide you feedbacks if I encounter any issues.

I have one suggestion for an additional feature you could provide, that is enabling ethernet over USB as it is done in the image that you find in the on-board eMMC. Do you think it would be useful?

Also, in the LISA Wiki I explain how to set up the tool for using the BeagleBone black with the ACME Cape and the iio infrastructure to measure energy ([instructions here](https://github.com/ARM-software/lisa/wiki/Energy-Meters-Requirements#iiocapture---baylibre-acme-cape)). Would it be okay if there I put the link to this beta image explicitly saying it is a beta?

Regards,
Michele

**Comment by superna9999** [comment]
OK, great news.

Yes, it's a good idea, and what about a ttyACM also to have a console ?
If you have other suggestions, I'll be happy to evaluate them.

Yes, you can add it to the LISA wiki, I'll give you a hint when we finally decided the final release.

Thanks,
Neil

**Comment by mdigiorgio** [comment]
Yes, that would be great as well. In fact, so far I've had to remove the ACME Cape to be able to have a serial console, this would solve this issue.

Thanks,
Michele

**Comment by mtitinger** [comment]
Hello,

I just updated the Baylibre wiki to reference the yocto/poky build flow, as I no longer see a reason to keep the more DIY buildroot scheme.

Cheers,
Marc.

**Comment by mdigiorgio** [comment]
This has been solved. I created a new issue (actually a feature request) to keep track of the ethernet over USB feature that could be added to the build.
